/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_ges_proyecto2022.presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sis_ges_proyecto2022.excepciones.AfiliacionException;
import sis_ges_proyecto2022.excepciones.AfiliacionesException;
import sis_ges_proyecto2022.logica.Afiliado;
import sis_ges_proyecto2022.logica.Afiliados;
import sis_ges_proyecto2022.logica.FachadaLogica;

/**
 *
 * @author mauri
 */
public class VentanaBuscarAfiliado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscarAfiliado
     */
    public VentanaBuscarAfiliado() {
        initComponents();
        
        estado.setText("activo");
        
        Afiliados afiliados = FachadaLogica.listaAfiliados();
            DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
            tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

//5es la cantidad de columnas

            Object[] datoFila = new Object[4];
            for (int i= 0; i < afiliados.getAfiliados().size(); i++) {

                Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);

                datoFila[0] = afiliado.getDocumento();
                datoFila[1] = afiliado.getNombre();
                datoFila[2] = afiliado.getApellido();
                datoFila[3] = afiliado.getTelefono();
                //datoFila[4] = preg.getPuntos();

                modelo.addRow(datoFila);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAfiliado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscarDoc = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        estado = new javax.swing.JToggleButton();
        volver = new javax.swing.JButton();
        deudores = new javax.swing.JButton();
        desde1 = new javax.swing.JTextField();
        hasta1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaAfiliado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Apellido", "Telefono"
            }
        ));
        tablaAfiliado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAfiliadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAfiliado);

        jLabel1.setText("Buscar por documento:");

        buscarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDocActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        estado.setText("jToggleButton1");
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        deudores.setText("Deudores");
        deudores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deudoresActionPerformed(evt);
            }
        });

        desde1.setText("DD/MM/YYYY");
        desde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desde1ActionPerformed(evt);
            }
        });

        hasta1.setText("DD/MM/YYYY");

        jLabel2.setText("Desde");

        jLabel3.setText("Hasta");

        fechas.setText("Buscar");
        fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(desde1)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hasta1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fechas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(estado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deudores)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(estado)
                    .addComponent(deudores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(fechas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(volver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarDocActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        String documento = this.buscarDoc.getText();
        Afiliado afiliado = new Afiliado();
        afiliado.setDocumento(documento);
        try {
            boolean existe = FachadaLogica.existeAfiliado(afiliado);
            String estado1 = FachadaLogica.estadoAfiliado(documento);
            if (existe){
                if (estado.getText().equals(estado1)){
                    afiliado = FachadaLogica.buscarAfiliado(documento);
                
                    DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
                    modelo.setRowCount(0);
                    Object[] datoFila = new Object[4];
                    datoFila[0] = afiliado.getDocumento();
                    datoFila[1] = afiliado.getNombre();
                    datoFila[2] = afiliado.getApellido();
                    datoFila[3] = afiliado.getTelefono();
                    modelo.addRow(datoFila);
                } else {
                    JLabel mensajeLbl = new JLabel();
                    JOptionPane.showMessageDialog(mensajeLbl, "Estado incompatible");
                }
                
                
            } else {
                JLabel mensajeLbl = new JLabel();
                JOptionPane.showMessageDialog(mensajeLbl, "Usuario no existe");
            }
        } catch (AfiliacionException ex) {
            Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    private void tablaAfiliadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAfiliadoMouseClicked
        // TODO add your handling code here:
        TableModel model = tablaAfiliado.getModel();
        int index = tablaAfiliado.getSelectedRow();
        String documento = (String) model.getValueAt(index, 0);
        //System.out.println(documento);
        new VentanaModificarAfiliado(documento, estado.getText()).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_tablaAfiliadoMouseClicked

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
        if (estado.getText().equals("activo")){
            estado.setText("inactivo");
            Afiliados afiliados = FachadaLogica.listaAfiliadosN();
            DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
            modelo.setRowCount(0);
            tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            //5es la cantidad de columnas
            
            Object[] datoFila = new Object[4];
            for (int i= 0; i < afiliados.getAfiliados().size(); i++) {
                
                Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);
                
                datoFila[0] = afiliado.getDocumento();
                datoFila[1] = afiliado.getNombre();
                datoFila[2] = afiliado.getApellido();
                datoFila[3] = afiliado.getTelefono();
                //datoFila[4] = preg.getPuntos();
                
                modelo.addRow(datoFila);
            }
        } else {
            estado.setText("activo");
            Afiliados afiliados = FachadaLogica.listaAfiliados();
            DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
            modelo.setRowCount(0);
            tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            //5es la cantidad de columnas
            
            Object[] datoFila = new Object[4];
            for (int i= 0; i < afiliados.getAfiliados().size(); i++) {
                
                Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);
                
                datoFila[0] = afiliado.getDocumento();
                datoFila[1] = afiliado.getNombre();
                datoFila[2] = afiliado.getApellido();
                datoFila[3] = afiliado.getTelefono();
                //datoFila[4] = preg.getPuntos();
                
                modelo.addRow(datoFila);
            }
        }
    }//GEN-LAST:event_estadoActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        new VentanaMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void deudoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deudoresActionPerformed
        // TODO add your handling code here:
        if (estado.getText().equals("activo")){
            try {
                Afiliados afiliados = FachadaLogica.buscarDeudores();
                DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
                modelo.setRowCount(0);
                tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
                //5es la cantidad de columnas
                
                Object[] datoFila = new Object[4];
                for (int i= 0; i < afiliados.getAfiliados().size(); i++) {
                    
                    Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);
                    
                    datoFila[0] = afiliado.getDocumento();
                    datoFila[1] = afiliado.getNombre();
                    datoFila[2] = afiliado.getApellido();
                    datoFila[3] = afiliado.getTelefono();
                    //datoFila[4] = preg.getPuntos();

                    modelo.addRow(datoFila);
                }
            } catch (AfiliacionesException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                Afiliados afiliados = FachadaLogica.buscarDeudoresN();
                DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
                modelo.setRowCount(0);
                tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
                //5es la cantidad de columnas
                
                Object[] datoFila = new Object[4];
                for (int i= 0; i < afiliados.getAfiliados().size(); i++) {
                    
                    Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);
                    
                    datoFila[0] = afiliado.getDocumento();
                    datoFila[1] = afiliado.getNombre();
                    datoFila[2] = afiliado.getApellido();
                    datoFila[3] = afiliado.getTelefono();
                    //datoFila[4] = preg.getPuntos();

                    modelo.addRow(datoFila);
                }
            } catch (AfiliacionesException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deudoresActionPerformed

    private void fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechasActionPerformed
        // TODO add your handling code here:
        String desde = this.desde1.getText();
        String hasta = this.hasta1.getText();
        
        if (estado.getText().equals("activo")){
            try {
                Afiliados afiliados = FachadaLogica.buscarFechas(desde, hasta);
                DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
                modelo.setRowCount(0);
                tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
                //5es la cantidad de columnas
                
                Object[] datoFila = new Object[4];
                for (int i= 0; i < afiliados.getAfiliados().size(); i++) {
                    
                    Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);
                    
                    datoFila[0] = afiliado.getDocumento();
                    datoFila[1] = afiliado.getNombre();
                    datoFila[2] = afiliado.getApellido();
                    datoFila[3] = afiliado.getTelefono();
                    //datoFila[4] = preg.getPuntos();

                    modelo.addRow(datoFila);
                }
            } catch (AfiliacionesException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                Afiliados afiliados = FachadaLogica.buscarFechasN(desde, hasta);
                DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
                modelo.setRowCount(0);
                tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                
                //5es la cantidad de columnas
                
                Object[] datoFila = new Object[4];
                for (int i= 0; i < afiliados.getAfiliados().size(); i++) {
                    
                    Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);
                    
                    datoFila[0] = afiliado.getDocumento();
                    datoFila[1] = afiliado.getNombre();
                    datoFila[2] = afiliado.getApellido();
                    datoFila[3] = afiliado.getTelefono();
                    //datoFila[4] = preg.getPuntos();

                    modelo.addRow(datoFila);
                }
            } catch (AfiliacionesException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_fechasActionPerformed

    private void desde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desde1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desde1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarAfiliado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarDoc;
    private javax.swing.JTextField desde1;
    private javax.swing.JButton deudores;
    private javax.swing.JToggleButton estado;
    private javax.swing.JButton fechas;
    private javax.swing.JTextField hasta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAfiliado;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
