/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_ges_proyecto2022.presentacion;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sis_ges_proyecto2022.excepciones.AfiliacionException;
import sis_ges_proyecto2022.logica.Afiliado;
import sis_ges_proyecto2022.logica.Afiliados;
import sis_ges_proyecto2022.logica.FachadaLogica;

/**
 *
 * @author mauri
 */
public class VentanaBuscarAfiliado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscarAfiliado
     */
    public VentanaBuscarAfiliado() {
        initComponents();
        
        estado.setText("activo");
        
        Afiliados afiliados = FachadaLogica.listaAfiliados();
            DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
            tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

//5es la cantidad de columnas

            Object[] datoFila = new Object[4];
            for (int i= 0; i < afiliados.getAfiliados().size(); i++) {

                Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);

                datoFila[0] = afiliado.getDocumento();
                datoFila[1] = afiliado.getNombre();
                datoFila[2] = afiliado.getApellido();
                datoFila[3] = afiliado.getTelefono();
                //datoFila[4] = preg.getPuntos();

                modelo.addRow(datoFila);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAfiliado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscarDoc = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        estado = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaAfiliado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Apellido", "Telefono"
            }
        ));
        tablaAfiliado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAfiliadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAfiliado);

        jLabel1.setText("Buscar por documento:");

        buscarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDocActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        estado.setText("jToggleButton1");
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(estado))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarDocActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        String documento = this.buscarDoc.getText();
        Afiliado afiliado = new Afiliado();
        afiliado.setDocumento(documento);
        try {
            boolean existe = FachadaLogica.existeAfiliado(afiliado);
            String estado1 = FachadaLogica.estadoAfiliado(documento);
            if (existe){
                if (estado.getText().equals(estado1)){
                    afiliado = FachadaLogica.buscarAfiliado(documento);
                
                    DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
                    modelo.setRowCount(0);
                    Object[] datoFila = new Object[4];
                    datoFila[0] = afiliado.getDocumento();
                    datoFila[1] = afiliado.getNombre();
                    datoFila[2] = afiliado.getApellido();
                    datoFila[3] = afiliado.getTelefono();
                    modelo.addRow(datoFila);
                } else {
                    JLabel mensajeLbl = new JLabel();
                    JOptionPane.showMessageDialog(mensajeLbl, "Estado incompatible");
                }
                
                
            } else {
                JLabel mensajeLbl = new JLabel();
                JOptionPane.showMessageDialog(mensajeLbl, "Usuario no existe");
            }
        } catch (AfiliacionException ex) {
            Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    private void tablaAfiliadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAfiliadoMouseClicked
        // TODO add your handling code here:
        TableModel model = tablaAfiliado.getModel();
        int index = tablaAfiliado.getSelectedRow();
        String documento = (String) model.getValueAt(index, 0);
        //System.out.println(documento);
        new VentanaModificarAfiliado(documento, estado.getText()).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_tablaAfiliadoMouseClicked

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
        if (estado.getText().equals("activo")){
            estado.setText("inactivo");
            Afiliados afiliados = FachadaLogica.listaAfiliadosN();
            DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
            modelo.setRowCount(0);
            tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            //5es la cantidad de columnas

            Object[] datoFila = new Object[4];
            for (int i= 0; i < afiliados.getAfiliados().size(); i++) {

                Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);

                datoFila[0] = afiliado.getDocumento();
                datoFila[1] = afiliado.getNombre();
                datoFila[2] = afiliado.getApellido();
                datoFila[3] = afiliado.getTelefono();
                //datoFila[4] = preg.getPuntos();

                modelo.addRow(datoFila);
            }
        } else {
            estado.setText("activo");
            Afiliados afiliados = FachadaLogica.listaAfiliados();
            DefaultTableModel modelo = (DefaultTableModel) tablaAfiliado.getModel();
            modelo.setRowCount(0);
            tablaAfiliado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
            //5es la cantidad de columnas

            Object[] datoFila = new Object[4];
            for (int i= 0; i < afiliados.getAfiliados().size(); i++) {

                Afiliado afiliado = (Afiliado) afiliados.getAfiliados().get(i);

                datoFila[0] = afiliado.getDocumento();
                datoFila[1] = afiliado.getNombre();
                datoFila[2] = afiliado.getApellido();
                datoFila[3] = afiliado.getTelefono();
                //datoFila[4] = preg.getPuntos();

                modelo.addRow(datoFila);
            }
        }
    }//GEN-LAST:event_estadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarAfiliado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarDoc;
    private javax.swing.JToggleButton estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAfiliado;
    // End of variables declaration//GEN-END:variables
}
